development:
  adapter: postgresql
  encoding: unicode
  database: lunch_meet_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lunch_meet_test
  pool: 5
  username: postgres
  password: 